### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by 13627491210** [lxp-git/react-native-cocos2dx#1]
能不能重新发布一下， https://registry.npmjs.org/  失效了。  谢谢

**Comment by lxp-git** [comment]
@13627491210 用git仓库引用吧。后面没有投入生产，所以没发布。

yarn add https://github.com/Flickering-AI/react-native-cocos2dx.git

**Comment by 13627491210** [comment]
> @13627491210 用git仓库引用吧。后面没有投入生产，所以没发布。
> 
> yarn add https://github.com/Flickering-AI/react-native-cocos2dx.git

好的，我试试

**Comment by 13627491210** [comment]
> @13627491210 用git仓库引用吧。后面没有投入生产，所以没发布。
> 
> yarn add https://github.com/Flickering-AI/react-native-cocos2dx.git

大佬，导入之后 运行报错，我原生安卓不熟悉，可以帮忙看看吗 
<img width="771" alt="image" src="https://github.com/Flickering-AI/react-native-cocos2dx/assets/37203543/a025865c-762b-492b-ad51-c69b5008eb39">

**Comment by 13627491210** [comment]
> > @13627491210 用git仓库引用吧。后面没有投入生产，所以没发布。
> > yarn add https://github.com/Flickering-AI/react-native-cocos2dx.git
> 
> 大佬，导入之后 运行报错，我原生安卓不熟悉，可以帮忙看看吗 <img alt="image" width="771" src="https://private-user-images.githubusercontent.com/37203543/337199964-a025865c-762b-492b-ad51-c69b5008eb39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjUyNjYsIm5iZiI6MTcxNzY2NDk2NiwicGF0aCI6Ii8zNzIwMzU0My8zMzcxOTk5NjQtYTAyNTg2NWMtNzYyYi00OTJiLWFkNTEtYzY5YjUwMDhlYjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5MDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MDdjMmY3YmExOWE4MjlmM2MwZjE3NjkyNzFiNTIxYzUzOGNhMDRiYmI1MmUwODZlNWM3ZWNhNWI1NGRkMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y5KttTdSxA4WjkIPmAnFLtSMwg6kI-SemS_glFPvD50">

方便的话，可以加个Q吗？我Q 728282535   都是做RN的
